<script setup lang="ts">
import { computed } from 'vue'; import { Head, Link, useForm } from '@inertiajs/vue3'; import InventoryNav from '../../Components/Common/InventoryNav.vue';
interface Customer{id:number;code:string;name:string} interface Location{id:number;name:string;warehouse:string} interface Product{id:number;sku:string;name:string;sale_price:string;unit_id:number;unit:string} interface Treasury{id:number;name:string;type:string}
const props=defineProps<{customers:Customer[];locations:Location[];products:Product[];treasuryAccounts:Treasury[]}>();
type Line={product_id:number|string;unit_id:number|string;quantity:number;unit_price:number;discount:number;tax_rate:number};
const form=useForm({operation_key:crypto.randomUUID(),customer_id:'',location_id:'',document_date:new Date().toISOString().slice(0,10),payment_type:'cash',payment_method:'cash',treasury_account_id:'',paid_amount:0,notes:'',lines:[{product_id:'',unit_id:'',quantity:1,unit_price:0,discount:0,tax_rate:15}] as Line[]});
const productChanged=(line:Line)=>{const p=props.products.find(x=>x.id===Number(line.product_id));if(p){line.unit_id=p.unit_id;line.unit_price=Number(p.sale_price)}};
const add=()=>form.lines.push({product_id:'',unit_id:'',quantity:1,unit_price:0,discount:0,tax_rate:15}); const remove=(i:number)=>{if(form.lines.length>1)form.lines.splice(i,1)};
const totals=computed(()=>form.lines.reduce((a,l)=>{const gross=l.quantity*l.unit_price;const net=Math.max(0,gross-l.discount);const tax=net*l.tax_rate/100;return{subtotal:a.subtotal+gross,discount:a.discount+l.discount,tax:a.tax+tax,total:a.total+net+tax}},{subtotal:0,discount:0,tax:0,total:0}));
const errorOf=(errors:unknown,key:string)=>(errors as Record<string,string>)[key];
const syncPayment=()=>{if(form.payment_type==='cash')form.paid_amount=Number(totals.value.total.toFixed(2))}; const submit=()=>{syncPayment();form.post('/sales')};
</script>
<template><Head title="Nueva venta"/><main class="page"><InventoryNav/><h1>Nueva venta</h1><p>Al confirmar se descuenta inventario y se genera el asiento contable.</p><form @submit.prevent="submit"><section class="card grid"><label>Cliente *<select v-model="form.customer_id" required><option value="">Selecciona</option><option v-for="c in customers" :key="c.id" :value="c.id">{{c.code}} — {{c.name}}</option></select></label><label>Ubicación de salida *<select v-model="form.location_id" required><option value="">Selecciona</option><option v-for="l in locations" :key="l.id" :value="l.id">{{l.warehouse}} / {{l.name}}</option></select></label><label>Fecha *<input v-model="form.document_date" type="date" required></label><label>Tipo de pago<select v-model="form.payment_type" @change="syncPayment"><option value="cash">Contado</option><option value="credit">Crédito</option></select></label><label>Método<select v-model="form.payment_method"><option value="cash">Efectivo</option><option value="bank_transfer">Transferencia</option><option value="card">Tarjeta</option><option value="other">Otro</option></select></label><label>Caja o banco *<select v-model="form.treasury_account_id" required><option value="">Selecciona</option><option v-for="a in treasuryAccounts" :key="a.id" :value="a.id">{{a.name}}</option></select></label><label>Monto pagado<input v-model.number="form.paid_amount" :readonly="form.payment_type==='cash'" type="number" min="0" step=".01"></label><label class="wide">Notas<textarea v-model="form.notes"/></label></section><section class="card"><h2>Productos</h2><div v-for="(line,i) in form.lines" :key="i" class="line"><select v-model="line.product_id" required @change="productChanged(line)"><option value="">Producto</option><option v-for="p in products" :key="p.id" :value="p.id">{{p.sku}} — {{p.name}} ({{p.unit}})</option></select><input v-model.number="line.quantity" type="number" min=".0001" step=".0001" placeholder="Cantidad" required><input v-model.number="line.unit_price" type="number" min="0" step=".0001" placeholder="Precio" required><input v-model.number="line.discount" type="number" min="0" step=".01" placeholder="Descuento"><input v-model.number="line.tax_rate" type="number" min="0" max="100" step=".01" placeholder="Impuesto %"><button type="button" class="danger" @click="remove(i)">×</button></div><button type="button" class="secondary" @click="add">+ Agregar producto</button><div class="totals"><span>Subtotal: {{totals.subtotal.toFixed(2)}}</span><span>Descuento: {{totals.discount.toFixed(2)}}</span><span>Impuesto: {{totals.tax.toFixed(2)}}</span><strong>Total: {{totals.total.toFixed(2)}}</strong></div></section><p class="error">{{errorOf(form.errors,'sale') || Object.values(form.errors)[0]}}</p><div class="actions"><Link href="/sales">Cancelar</Link><button :disabled="form.processing">Confirmar venta</button></div></form></main></template>
<style scoped>.page{max-width:1500px;margin:auto;padding:2rem}.card{padding:1.5rem;border:1px solid var(--p-content-border-color);border-radius:1rem;margin:1rem 0;background:var(--p-content-background)}.grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:1rem}.wide{grid-column:1/-1}label{display:grid;gap:.4rem;font-weight:600}input,select,textarea{padding:.75rem;border:1px solid var(--p-content-border-color);border-radius:.5rem;background:transparent;color:inherit;min-width:0}textarea{min-height:5rem}.line{display:grid;grid-template-columns:2fr repeat(4,1fr) auto;gap:.6rem;margin-bottom:.7rem}.totals,.actions{display:flex;justify-content:flex-end;gap:1.5rem;flex-wrap:wrap;margin-top:1rem}.actions a,button{padding:.7rem 1rem;border:0;border-radius:.5rem;background:var(--p-primary-color);color:var(--p-primary-contrast-color);font-weight:700;text-decoration:none}.actions a,.secondary{background:transparent;color:inherit;border:1px solid var(--p-content-border-color)}.danger{background:#ef4444}.error{color:#ef4444}@media(max-width:900px){.grid{grid-template-columns:1fr}.wide{grid-column:auto}.line{grid-template-columns:1fr 1fr}.line select{grid-column:1/-1}}</style>
