<script setup lang="ts">
import { Head, Link, useForm } from '@inertiajs/vue3'; import InventoryNav from '../../Components/Common/InventoryNav.vue';
interface Sale{id:number;number:string;document_date:string;customer:string;payment_type:string;status:string;total:string;paid_amount:string}
defineProps<{sales:Sale[]}>(); const payment=useForm({payment_date:new Date().toISOString().slice(0,10),amount:0,method:'cash',reference:'',notes:''}); let selected=0;
const errorOf=(errors:unknown,key:string)=>(errors as Record<string,string>)[key];
const pay=(id:number)=>{selected=id;payment.post(`/sales/${id}/payments`,{preserveScroll:true,onSuccess:()=>{payment.reset('amount','reference','notes');selected=0}})};
</script>
<template><Head title="Ventas"/><main class="page"><InventoryNav/><header><div><h1>Ventas</h1><p>Documentos confirmados, cobros y saldos pendientes.</p></div><div class="actions"><Link href="/sales/customers">Clientes</Link><Link class="primary" href="/sales/create">Nueva venta</Link></div></header><section class="card table"><table><thead><tr><th>Número</th><th>Fecha</th><th>Cliente</th><th>Tipo</th><th>Total</th><th>Pagado</th><th>Saldo</th><th>Cobro</th></tr></thead><tbody><tr v-for="s in sales" :key="s.id"><td>{{s.number}}</td><td>{{s.document_date}}</td><td>{{s.customer}}</td><td>{{s.payment_type==='cash'?'Contado':'Crédito'}}</td><td>{{s.total}}</td><td>{{s.paid_amount}}</td><td>{{(Number(s.total)-Number(s.paid_amount)).toFixed(2)}}</td><td><button v-if="Number(s.total)>Number(s.paid_amount)" @click="selected=selected===s.id?0:s.id">Registrar</button></td></tr></tbody></table></section><form v-if="selected" class="card pay" @submit.prevent="pay(selected)"><h2>Registrar cobro</h2><label>Fecha<input v-model="payment.payment_date" type="date" required></label><label>Monto<input v-model.number="payment.amount" type="number" min=".01" step=".01" required></label><label>Método<select v-model="payment.method"><option value="cash">Efectivo</option><option value="bank_transfer">Transferencia</option><option value="card">Tarjeta</option><option value="other">Otro</option></select></label><label>Referencia<input v-model="payment.reference"></label><button :disabled="payment.processing">Confirmar cobro</button><p class="error">{{errorOf(payment.errors,'payment')}}</p></form></main></template>
<style scoped>.page{max-width:1500px;margin:auto;padding:2rem}header,.actions,.pay{display:flex;gap:1rem;align-items:center;flex-wrap:wrap}header{justify-content:space-between}.actions a,button{padding:.7rem 1rem;border:1px solid var(--p-content-border-color);border-radius:.5rem;color:inherit;text-decoration:none;background:transparent}.actions .primary,button{background:var(--p-primary-color);color:var(--p-primary-contrast-color);border:0}.card{padding:1.5rem;border:1px solid var(--p-content-border-color);border-radius:1rem;margin-top:1rem;background:var(--p-content-background)}.table{overflow:auto}table{width:100%;border-collapse:collapse}th,td{text-align:left;padding:.8rem;border-bottom:1px solid var(--p-content-border-color)}label{display:grid;gap:.3rem}input,select{padding:.65rem;border:1px solid var(--p-content-border-color);border-radius:.5rem;background:transparent;color:inherit}.error{color:#ef4444}</style>
