<script setup lang="ts">
import { computed, ref } from 'vue';import {Head,router,useForm} from '@inertiajs/vue3';import Button from 'primevue/button';import Tag from 'primevue/tag';import { useI18n } from 'vue-i18n';import InventoryNav from '../../../Components/Common/InventoryNav.vue';
type Row=Record<string,unknown>&{id:number;active:boolean};
const props=defineProps<{units:Row[];categories:Row[];suppliers:Row[];warehouses:Row[];locations:Row[];product_units:Row[];catalog_products:Row[];catalog_units:Row[]}>();const tab=ref<'units'|'categories'|'suppliers'|'warehouses'|'locations'|'product-units'>('categories');
const { t }=useI18n();const tabs=['categories','units','product-units','suppliers','warehouses','locations'] as const;const tabLabels=computed<Record<(typeof tabs)[number],string>>(()=>({categories:t('inventory.catalogs.categories'),units:t('inventory.catalogs.units'),'product-units':t('inventory.catalogs.conversions'),suppliers:t('inventory.catalogs.suppliers'),warehouses:t('inventory.catalogs.warehouses'),locations:t('inventory.catalogs.locations')}));
const form=useForm({code:'',name:'',symbol:'',dimension:'quantity',decimal_places:0,description:'',sort_order:0,parent_id:null as number|null,legal_name:'',trade_name:'',tax_id:'',contact_name:'',email:'',phone:'',address:'',payment_terms_days:0,is_default:false,warehouse_id:'' as number|'',zone:'',aisle:'',rack:'',bin:'',product_id:'' as number|'',unit_id:'' as number|'',conversion_factor_to_base:'',is_purchase_unit:true,is_sale_unit:true,is_issue_unit:true});
const rows=computed(()=>tab.value==='product-units'?props.product_units:props[tab.value]);const title=computed(()=>tabLabels.value[tab.value]);
function submit(){form.post(`/inventory/catalogs/${tab.value}`,{preserveScroll:true,onSuccess:()=>form.reset()})}function toggle(row:Row){router.patch(`/inventory/catalogs/${tab.value}/${row.id}/active`,{active:!row.active},{preserveScroll:true})}function label(row:Row){if(tab.value==='suppliers')return String(row.legal_name);if(tab.value==='product-units')return `${String(row.sku)} — ${String(row.product_name)} / ${String(row.unit_name)}`;return String(row.name)}
function selectTab(key:(typeof tabs)[number]){tab.value=key;form.clearErrors()}
</script>
<template><Head :title="`${t('inventory.catalogs.pageTitle')} | ${t('common.appName')}`"/><main class="page"><InventoryNav/><h1>{{t('inventory.catalogs.title')}}</h1><p class="lead">{{t('inventory.catalogs.lead')}}</p><div class="tabs" role="tablist"><Button v-for="key in tabs" :key="key" :label="tabLabels[key]" :severity="tab===key?'primary':'secondary'" :outlined="tab!==key" @click="selectTab(key)"/></div>
<section class="panel"><h2>{{t('inventory.catalogs.newRecord',{catalog:title.toLowerCase()})}}</h2><div class="grid">
<template v-if="tab==='units'"><label>{{t('common.code')}} *<input v-model.trim="form.code"/></label><label>{{t('common.name')}} *<input v-model.trim="form.name"/></label><label>{{t('inventory.catalogs.symbol')}} *<input v-model.trim="form.symbol"/></label><label>{{t('inventory.catalogs.dimension')}} *<select v-model="form.dimension"><option value="quantity">{{t('inventory.catalogs.quantity')}}</option><option value="length">{{t('inventory.catalogs.length')}}</option><option value="area">{{t('inventory.catalogs.area')}}</option><option value="weight">{{t('inventory.catalogs.weight')}}</option><option value="volume">{{t('inventory.catalogs.volume')}}</option></select></label><label>{{t('inventory.catalogs.decimals')}} *<input v-model.number="form.decimal_places" type="number" min="0" max="4"/></label></template>
<template v-else-if="tab==='categories'"><label>{{t('common.code')}} *<input v-model.trim="form.code"/></label><label>{{t('common.name')}} *<input v-model.trim="form.name"/></label><label>{{t('inventory.catalogs.parentCategory')}}<select v-model="form.parent_id"><option :value="null">{{t('common.none')}}</option><option v-for="c in categories" :key="c.id" :value="c.id">{{c.name}}</option></select></label><label>{{t('inventory.catalogs.order')}}<input v-model.number="form.sort_order" type="number" min="0"/></label><label class="wide">{{t('common.description')}}<textarea v-model.trim="form.description"/></label></template>
<template v-else-if="tab==='product-units'"><label>{{t('common.product')}} *<select v-model="form.product_id"><option value="">{{t('common.select')}}</option><option v-for="p in catalog_products" :key="p.id" :value="p.id">{{p.sku}} — {{p.name}}</option></select></label><label>{{t('inventory.catalogs.alternateUnit')}} *<select v-model="form.unit_id"><option value="">{{t('common.select')}}</option><option v-for="u in catalog_units" :key="u.id" :value="u.id">{{u.name}} ({{u.symbol}})</option></select></label><label>{{t('inventory.catalogs.factor')}} *<input v-model.trim="form.conversion_factor_to_base" inputmode="decimal" :placeholder="t('inventory.catalogs.factorExample')"/></label><label class="check"><input v-model="form.is_purchase_unit" type="checkbox"/> {{t('inventory.catalogs.purchaseAvailable')}}</label><label class="check"><input v-model="form.is_sale_unit" type="checkbox"/> {{t('inventory.catalogs.saleAvailable')}}</label><label class="check"><input v-model="form.is_issue_unit" type="checkbox"/> {{t('inventory.catalogs.issueAvailable')}}</label></template>
<template v-else-if="tab==='suppliers'"><label>{{t('common.code')}} *<input v-model.trim="form.code"/></label><label>{{t('inventory.catalogs.legalName')}} *<input v-model.trim="form.legal_name"/></label><label>{{t('inventory.catalogs.tradeName')}}<input v-model.trim="form.trade_name"/></label><label>{{t('inventory.catalogs.taxId')}}<input v-model.trim="form.tax_id"/></label><label>{{t('inventory.catalogs.contact')}}<input v-model.trim="form.contact_name"/></label><label>{{t('inventory.catalogs.email')}}<input v-model.trim="form.email" type="email"/></label><label>{{t('inventory.catalogs.phone')}}<input v-model.trim="form.phone"/></label><label>{{t('inventory.catalogs.creditDays')}}<input v-model.number="form.payment_terms_days" type="number" min="0"/></label><label class="wide">{{t('inventory.catalogs.address')}}<textarea v-model.trim="form.address"/></label></template>
<template v-else-if="tab==='warehouses'"><label>{{t('common.code')}} *<input v-model.trim="form.code"/></label><label>{{t('common.name')}} *<input v-model.trim="form.name"/></label><label>{{t('inventory.catalogs.phone')}}<input v-model.trim="form.phone"/></label><label class="check"><input v-model="form.is_default" type="checkbox"/> {{t('inventory.catalogs.defaultWarehouse')}}</label><label class="wide">{{t('inventory.catalogs.address')}}<textarea v-model.trim="form.address"/></label></template>
<template v-else><label>{{t('common.warehouse')}} *<select v-model="form.warehouse_id"><option value="">{{t('common.select')}}</option><option v-for="w in warehouses" :key="w.id" :value="w.id">{{w.name}}</option></select></label><label>{{t('common.code')}} *<input v-model.trim="form.code"/></label><label>{{t('common.name')}} *<input v-model.trim="form.name"/></label><label>{{t('inventory.catalogs.zone')}}<input v-model.trim="form.zone"/></label><label>{{t('inventory.catalogs.aisle')}}<input v-model.trim="form.aisle"/></label><label>{{t('inventory.catalogs.rack')}}<input v-model.trim="form.rack"/></label><label>{{t('inventory.catalogs.bin')}}<input v-model.trim="form.bin"/></label></template>
</div><ul v-if="Object.keys(form.errors).length" class="errors"><li v-for="(e,k) in form.errors" :key="k">{{e}}</li></ul><Button :label="t('inventory.catalogs.save')" icon="pi pi-save" :loading="form.processing" @click="submit"/></section>
<section class="panel"><h2>{{t('inventory.catalogs.registered',{catalog:title})}}</h2><div class="table"><table><thead><tr><th>{{tab==='product-units'?t('inventory.catalogs.factor'):t('common.code')}}</th><th>{{t('common.name')}}</th><th v-if="tab==='locations'">{{t('common.warehouse')}}</th><th>{{t('common.status')}}</th><th>{{t('common.action')}}</th></tr></thead><tbody><tr v-for="row in rows" :key="row.id"><td>{{tab==='product-units'?row.conversion_factor_to_base:row.code}}</td><td>{{label(row)}}</td><td v-if="tab==='locations'">{{row.warehouse_name}}</td><td><Tag :severity="row.active?'success':'secondary'" :value="row.active?t('common.active'):t('common.inactive')"/></td><td><Button :label="row.active?t('common.deactivate'):t('common.activate')" :severity="row.active?'danger':'success'" size="small" @click="toggle(row)"/></td></tr></tbody></table></div></section></main></template>
<style scoped>.page{max-width:1200px;margin:auto;padding:clamp(1rem,3vw,2.5rem);font-family:system-ui,sans-serif}.lead{color:var(--p-text-muted-color)}.tabs{display:flex;gap:.5rem;flex-wrap:wrap;margin:1.5rem 0}.panel{margin-top:1rem;padding:1.4rem;border:1px solid var(--p-content-border-color);border-radius:1rem;background:var(--p-content-background)}.grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:1rem;margin-bottom:1rem}.wide{grid-column:1/-1}label{display:grid;gap:.4rem;font-weight:650}.check{display:flex;align-items:center}.check input{width:auto}input,select,textarea{padding:.7rem;border:1px solid var(--p-content-border-color);border-radius:.5rem;background:var(--p-form-field-background);color:var(--p-text-color)}textarea{min-height:4rem}.errors{color:var(--p-red-400)}.table{overflow-x:auto}table{width:100%;border-collapse:collapse}th,td{padding:.75rem;border-bottom:1px solid var(--p-content-border-color);text-align:left}@media(max-width:700px){.grid{grid-template-columns:1fr}.wide{grid-column:auto}}</style>
