<script setup lang="ts">
import { computed } from 'vue'; import { Link,usePage } from '@inertiajs/vue3';
defineProps<{open:boolean}>(); defineEmits<{close:[]}>();
const page=usePage<{auth:{permissions:string[];user:{name:string;email:string}|null}}>();const permissions=computed(()=>page.props.auth.permissions??[]);const can=(p:string)=>permissions.value.includes(p);
const groups=computed(()=>[
{label:'Principal',items:[{label:'Dashboard',icon:'pi-home',href:'/',show:true}]},
{label:'Inventario',items:[{label:'Productos',icon:'pi-box',href:'/inventory/products',show:can('inventory.products.view')},{label:'Entradas',icon:'pi-arrow-down',href:'/inventory/entries/create',show:can('inventory.entries.create')},{label:'Salidas',icon:'pi-arrow-up',href:'/inventory/exits/create',show:can('inventory.exits.create')},{label:'Kardex',icon:'pi-list',href:'/inventory/kardex',show:can('inventory.kardex.view')},{label:'Conteos',icon:'pi-clipboard',href:'/inventory/counts',show:can('inventory.counts.view')},{label:'Alertas',icon:'pi-bell',href:'/inventory/alerts',show:can('inventory.alerts.view')}]},
{label:'Comercial',items:[{label:'Ventas',icon:'pi-shopping-cart',href:'/sales',show:can('sales.view')},{label:'Clientes',icon:'pi-users',href:'/sales/customers',show:can('sales.customers.manage')},{label:'Compras',icon:'pi-shopping-bag',href:'/purchases',show:can('purchases.view')},{label:'Proveedores',icon:'pi-truck',href:'/suppliers',show:can('suppliers.view')}]},
{label:'Contabilidad',items:[{label:'Resumen contable',icon:'pi-calculator',href:'/accounting',show:can('accounting.entries.view')},{label:'Caja y bancos',icon:'pi-wallet',href:'/accounting/treasury',show:can('accounting.treasury.view')},{label:'Gastos y servicios',icon:'pi-receipt',href:'/accounting/expenses',show:can('accounting.expenses.view')},{label:'Préstamos y vehículos',icon:'pi-car',href:'/accounting/loans',show:can('accounting.loans.view')}]},
{label:'Administración',items:[{label:'Usuarios y roles',icon:'pi-shield',href:'/access',show:can('access.users.view')},{label:'Catálogos',icon:'pi-cog',href:'/inventory/catalogs',show:can('inventory.catalogs.view')}]},
].map(g=>({...g,items:g.items.filter(i=>i.show)})).filter(g=>g.items.length));
const active=(href:string)=>href==='/'?page.url==='/':page.url.startsWith(href);
</script>
<template><aside :class="['sidebar',{open}]"><div class="brand"><div class="logo">VM</div><div><strong>Vidriería Maradiaga</strong><small>Sistema ERP</small></div><button class="close" aria-label="Cerrar menú" @click="$emit('close')"><i class="pi pi-times"/></button></div><nav><section v-for="g in groups" :key="g.label"><p>{{g.label}}</p><Link v-for="i in g.items" :key="i.href" :href="i.href" :class="{active:active(i.href)}" @click="$emit('close')"><i :class="['pi',i.icon]"/><span>{{i.label}}</span></Link></section></nav><div class="user"><span class="avatar">{{page.props.auth.user?.name?.charAt(0).toUpperCase()||'U'}}</span><div><strong>{{page.props.auth.user?.name}}</strong><small>{{page.props.auth.user?.email}}</small></div></div></aside><div v-if="open" class="backdrop" @click="$emit('close')"/></template>
<style scoped>.sidebar{position:fixed;inset:0 auto 0 0;width:17rem;background:#0b1220;color:#dbe4f0;z-index:40;display:flex;flex-direction:column;box-shadow:10px 0 30px #0f172a1a}.brand{height:4.5rem;display:flex;align-items:center;gap:.75rem;padding:0 1rem;border-bottom:1px solid #ffffff16}.logo{width:2.25rem;height:2.25rem;border-radius:.65rem;background:linear-gradient(135deg,#3b82f6,#06b6d4);display:grid;place-items:center;color:white;font-weight:900}.brand strong,.brand small,.user strong,.user small{display:block}.brand small,.user small{font-size:.72rem;color:#8fa2ba}.close{display:none;margin-left:auto;background:none;border:0;color:white}nav{padding:.75rem;overflow:auto;flex:1}nav section{margin-bottom:1rem}nav p{margin:.45rem .65rem;color:#71849d;font-size:.68rem;text-transform:uppercase;letter-spacing:.12em;font-weight:800}nav a{display:flex;align-items:center;gap:.75rem;color:#c6d2e1;text-decoration:none;padding:.68rem .75rem;border-radius:.55rem;margin:.12rem 0;font-size:.9rem}nav a:hover,nav a.active{background:#2563eb;color:white}.user{display:flex;align-items:center;gap:.7rem;padding:1rem;border-top:1px solid #ffffff16;min-width:0}.user div{min-width:0}.user strong,.user small{overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.avatar{flex:0 0 auto;width:2rem;height:2rem;border-radius:50%;display:grid;place-items:center;background:#1e3a5f;color:#93c5fd;font-weight:800}.backdrop{display:none}@media(max-width:950px){.sidebar{transform:translateX(-105%);transition:transform .2s}.sidebar.open{transform:translateX(0)}.close{display:block}.backdrop{display:block;position:fixed;inset:0;background:#0008;z-index:35}}</style>
