<script setup lang="ts">
import { computed, ref } from 'vue';
import { Head, Link, useForm, usePage } from '@inertiajs/vue3';
import InventoryNav from '../../Components/Common/InventoryNav.vue';
interface Purchase { id:number; number:string; supplier_document:string|null; document_date:string; due_date:string|null; supplier:string; payment_type:string; status:string; total:string; paid_amount:string }
interface Treasury { id:number; name:string; type:string }
const props=defineProps<{purchases:Purchase[];treasuryAccounts:Treasury[]}>();
const page=usePage<{auth:{permissions:string[]};flash?:{success?:string}}>();
const canPay=computed(()=>page.props.auth.permissions.includes('purchases.payments.manage'));
const selected=ref<Purchase|null>(null);
const payment=useForm({payment_date:new Date().toISOString().slice(0,10),amount:0,treasury_account_id:'',method:'bank_transfer',reference:'',notes:''});
const money=(v:string|number)=>new Intl.NumberFormat('es-HN',{style:'currency',currency:'HNL'}).format(Number(v));
const balance=(p:Purchase)=>Math.max(0,Number(p.total)-Number(p.paid_amount));
const openPayment=(p:Purchase)=>{selected.value=p;payment.amount=balance(p)};
const submitPayment=()=>{if(!selected.value)return;payment.post(`/purchases/${selected.value.id}/payments`,{preserveScroll:true,onSuccess:()=>{selected.value=null;payment.reset()}})};
</script>
<template>
<Head title="Compras y cuentas por pagar"/><main class="page"><InventoryNav/>
<header class="heading"><div><p class="eyebrow">COMPRAS</p><h1>Compras y cuentas por pagar</h1><p>Registra materiales recibidos, facturas de proveedores y pagos pendientes.</p></div><Link v-if="page.props.auth.permissions.includes('purchases.create')" href="/purchases/create" class="primary"><i class="pi pi-plus"/> Nueva compra</Link></header>
<p v-if="page.props.flash?.success" class="success">{{page.props.flash.success}}</p>
<section class="card table"><table><thead><tr><th>Compra</th><th>Fecha</th><th>Proveedor</th><th>Factura</th><th>Vence</th><th class="right">Total</th><th class="right">Saldo</th><th>Estado</th><th></th></tr></thead><tbody>
<tr v-for="p in purchases" :key="p.id"><td>{{p.number}}</td><td>{{p.document_date}}</td><td>{{p.supplier}}</td><td>{{p.supplier_document||'—'}}</td><td>{{p.due_date||'—'}}</td><td class="right">{{money(p.total)}}</td><td class="right">{{money(balance(p))}}</td><td><span :class="['badge',balance(p)>0?'pending':'paid']">{{balance(p)>0?'Pendiente':'Pagada'}}</span></td><td><button v-if="canPay&&balance(p)>0" class="link" @click="openPayment(p)">Registrar pago</button></td></tr>
<tr v-if="!purchases.length"><td colspan="9">No hay compras registradas.</td></tr></tbody></table></section>
<div v-if="selected" class="overlay" @click.self="selected=null"><form class="modal" @submit.prevent="submitPayment"><h2>Pago de {{selected.number}}</h2><p>Saldo: <strong>{{money(balance(selected))}}</strong></p><label>Fecha<input v-model="payment.payment_date" type="date" required></label><label>Monto<input v-model.number="payment.amount" type="number" min=".01" :max="balance(selected)" step=".01" required></label><label>Cuenta de pago<select v-model="payment.treasury_account_id" required><option value="">Selecciona</option><option v-for="a in treasuryAccounts" :key="a.id" :value="a.id">{{a.name}}</option></select></label><label>Método<select v-model="payment.method"><option value="cash">Efectivo</option><option value="bank_transfer">Transferencia</option><option value="card">Tarjeta</option><option value="check">Cheque</option><option value="other">Otro</option></select></label><label>Referencia<input v-model="payment.reference"></label><p class="error">{{Object.values(payment.errors)[0]}}</p><div class="actions"><button type="button" class="secondary" @click="selected=null">Cancelar</button><button :disabled="payment.processing">Confirmar pago</button></div></form></div>
</main></template>
<style scoped>.page{max-width:1500px;margin:auto;padding:2rem}.heading{display:flex;justify-content:space-between;gap:1rem;align-items:center}.eyebrow{color:var(--p-primary-color);font-weight:800;font-size:.75rem;letter-spacing:.15em}.primary,button{display:inline-flex;align-items:center;gap:.5rem;padding:.75rem 1rem;border:0;border-radius:.6rem;background:var(--p-primary-color);color:var(--p-primary-contrast-color);font-weight:700;text-decoration:none}.card{padding:1.25rem;border:1px solid var(--p-content-border-color);border-radius:1rem;background:var(--p-content-background);margin-top:1.5rem}.table{overflow:auto}table{width:100%;border-collapse:collapse}th,td{padding:.85rem;border-bottom:1px solid var(--p-content-border-color);text-align:left;white-space:nowrap}.right{text-align:right}.badge{padding:.25rem .55rem;border-radius:999px;font-weight:700;font-size:.8rem}.pending{background:#fef3c7;color:#92400e}.paid,.success{background:#dcfce7;color:#166534}.success{padding:.75rem;border-radius:.5rem}.link{background:transparent;color:var(--p-primary-color);padding:.35rem}.overlay{position:fixed;inset:0;background:#0008;display:grid;place-items:center;padding:1rem;z-index:50}.modal{width:min(34rem,100%);padding:1.5rem;border-radius:1rem;background:var(--p-content-background);display:grid;gap:1rem}.modal label{display:grid;gap:.35rem;font-weight:600}.modal input,.modal select{padding:.7rem;border:1px solid var(--p-content-border-color);border-radius:.5rem;background:transparent;color:inherit}.actions{display:flex;justify-content:flex-end;gap:.7rem}.secondary{background:transparent;color:inherit;border:1px solid var(--p-content-border-color)}.error{color:#dc2626}@media(max-width:700px){.page{padding:1rem}.heading{align-items:flex-start;flex-direction:column}}</style>
